### ISSUE TITLE
error returned from database: 1146 (42S02): Table 'owncloud.nullmounts' doesn't exist

### ISSUE THREAD

**Issue by 4001982248998** [nextcloud/notify_push#33]
After starting the systemd unit, the binary complains about a missing database table. The connection to the database should be okay, as its (legacy) name really is “owncloud”.

Output with extended verbosity by ``RUST_BACKTRACE=1``:

```
Feb 24 12:27:20 myhost systemd[1]: Started Push daemon for Nextcloud clients.
Feb 24 12:27:20 myhost notify_push[3050316]: Error:
Feb 24 12:27:20 myhost notify_push[3050316]:    0: Failed to test database access
Feb 24 12:27:20 myhost notify_push[3050316]:    1: Failed to load storage mapping from database
Feb 24 12:27:20 myhost notify_push[3050316]:    2: error returned from database: 1146 (42S02): Table 'owncloud.nullmounts' doesn't exist
Feb 24 12:27:20 myhost notify_push[3050316]: Location:
Feb 24 12:27:20 myhost notify_push[3050316]:    /tmp/krankerl.6wDVzxnHMC1t/notify_push/src/storage_mapping.rs:108
Feb 24 12:27:20 myhost notify_push[3050316]:   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Feb 24 12:27:20 myhost notify_push[3050316]:                                  ⋮ 1 frame hidden ⋮                               
Feb 24 12:27:20 myhost notify_push[3050316]:    2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h37400b9659074ff9
Feb 24 12:27:20 myhost notify_push[3050316]:       at <unknown source file>:<unknown line>
Feb 24 12:27:20 myhost notify_push[3050316]:    3: notify_push::main::{{closure}}::h8353892e3b19db59
Feb 24 12:27:20 myhost notify_push[3050316]:       at <unknown source file>:<unknown line>
Feb 24 12:27:20 myhost notify_push[3050316]:    4: notify_push::main::h4f6958ef3c78b4fd
Feb 24 12:27:20 myhost notify_push[3050316]:       at <unknown source file>:<unknown line>
Feb 24 12:27:20 myhost notify_push[3050316]:    5: std::sys_common::backtrace::__rust_begin_short_backtrace::h35bee24ae9e94d86
Feb 24 12:27:20 myhost notify_push[3050316]:       at <unknown source file>:<unknown line>
Feb 24 12:27:20 myhost notify_push[3050316]:    6: main<unknown>
Feb 24 12:27:20 myhost notify_push[3050316]:       at <unknown source file>:<unknown line>
Feb 24 12:27:20 myhost notify_push[3050316]: Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Feb 24 12:27:20 myhost notify_push[3050316]: Run with RUST_BACKTRACE=full to include source snippets.
Feb 24 12:27:20 myhost systemd[1]: notify_push.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by Chartman123** [comment]
Did you use your config.php for the configuration? I had a similar problem in #30 and could fix it by providing the environment variable DATABASE_PREFIX. What's the value of "dbtableprefix" in your config.php?

**Comment by 4001982248998** [comment]
Yes, using config.php. Not using a prefix, the variable does not exist there.

I am missing the database table, I think:

```
$ sudo mysql
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 1644586
Server version: 10.3.25-MariaDB-0ubuntu0.20.04.1 Ubuntu 20.04

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> use owncloud;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [owncloud]> desc nullmounts;
ERROR 1146 (42S02): Table 'owncloud.nullmounts' doesn't exist
MariaDB [owncloud]> desc oc_users;
+-------------+--------------+------+-----+---------+-------+
| Field       | Type         | Null | Key | Default | Extra |
+-------------+--------------+------+-----+---------+-------+
| uid         | varchar(64)  | NO   | PRI |         |       |
| displayname | varchar(64)  | YES  |     | NULL    |       |
| password    | varchar(255) | NO   |     |         |       |
| uid_lower   | varchar(64)  | YES  | MUL |         |       |
+-------------+--------------+------+-----+---------+-------+
4 rows in set (0.002 sec)

MariaDB [owncloud]> desc oc_nullmounts;
ERROR 1146 (42S02): Table 'owncloud.oc_nullmounts' doesn't exist
```

**Comment by Chartman123** [comment]
Yes, the table is called prefix + "mounts". I think that in someway the string "null" is added as a prefix. Perhaps you could try to set the dbtableprefix to "" with `./occ config:system.set dbtableprefix --type string --value ""`

There must be an error in the config-parser of notify_push that adds the text "null" if the value isn't set inside config.php

**Comment by 4001982248998** [comment]
The sample configuration is:
```
/**                                                                                        
 * Prefix for the Nextcloud tables in the database.                                        
 *                                                                                         
 * Default to ``oc_``                                                                      
 */                                                                                        
'dbtableprefix' => '',
```

As all my tables have the default ``oc_`` prefix, and there really is no table with the name ``nullmounts``, either with or without prefix, I see little use in setting an empty dbtableprefix?

**Comment by Chartman123** [comment]
If your tables inside the database have the oc_ prefix this should be configured inside your config.php. You should find a table oc_mounts inside your db. This would of course only be a workaround...

To fix the problem in general, I think that the following line has to be changed in the parser: https://github.com/nextcloud/notify_push/blob/c7136a398162637ad04c142f64668c60afd1aac9/src/config.rs#L45

**Comment by icewind1991** [comment]
You should be to work around the issue for now by setting the `dbtableprefix` to the default `oc_` explicitly in your `config.php`, the next release will handle this case correctly.

**Comment by icewind1991** [comment]
Should be fixed with 0.1.4

**Comment by 4001982248998** [comment]
Please reopen. The issue still exists with both updated version to 0.1.4 and the ``dbtableprefix``.

The table is not existing, either with or without prefix.

**Comment by icewind1991** [comment]
Please post your `config.php` (with passwords redacted) and the output of `SHOW TABLES;`

**Comment by 4001982248998** [comment]
Hmmmm… I do not know why, but it *is* starting now, with both updated version and

```php
'dbtableprefix' => 'oc_',```
